-- Active: 1764023905842@@127.0.0.1@3306@StrangerDrug
CREATE DATABASE IF NOT EXISTS StrangerDrug;

USE StrangerDrug;

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE login_attempts(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(225) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    successful BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_agent VARCHAR(255)
);

CREATE TABLE refresh_tokens(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(500) NOT NULL,
    user_email VARCHAR(225) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP
);

CREATE TABLE videos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(500),
    video_type ENUM('MAIN', 'PREVIEW') NOT NULL
);

CREATE TABLE photos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(500) NOT NULL,
    photo_type ENUM('THUMBNAIL', 'PROFILE') NOT NULL
);

CREATE TABLE payments(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    transaction_id VARCHAR(255) NOT NULL,
    status ENUM('APPROVED', 'DECLINED', 'REFUNDED') NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(225) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    birthdate DATE NOT NULL,
    role ENUM('ADMIN', 'CLIENTE') NOT NULL
);

CREATE TABLE purchases(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_purchase_admin BOOLEAN NOT NULL DEFAULT TRUE,
    status_purchase_cliente BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY unique_purchase (payment_id, user_id, video_id)
);