-- Active: 1764023905842@@127.0.0.1@3306@StrangerDrug
CREATE DATABASE IF NOT EXISTS StrangerDrug;

USE StrangerDrug;

SET NAMES utf8mb4;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE login_attempts(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(225) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    successful BOOLEAN NOT NULL,
    failure_reason VARCHAR(255),
    attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_agent VARCHAR(255)
);

CREATE TABLE refresh_tokens(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(500) NOT NULL,
    user_email VARCHAR(225) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP
);

CREATE TABLE videos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(500),
    video_type ENUM('MAIN', 'PREVIEW') NOT NULL
);

CREATE TABLE photos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    s3_bucket VARCHAR(150) NOT NULL,
    s3_key VARCHAR(300) NOT NULL,
    s3_url VARCHAR(500) NOT NULL,
    photo_type ENUM('THUMBNAIL', 'PROFILE') NOT NULL
);